### ISSUE TITLE
Overwriting file?

### ISSUE THREAD

**Issue by Remty5** [deka0106/upload-to-dropbox#1]
I would like to automatically update a file on Dropbox, preferably without deleting it because it want it to be shared.
Is this even possible? Or would the sharing link change even if I overwrite the file?

Thank you for your Github Action.

Edit: I found [this](https://stackoverflow.com/questions/44518469/overwrite-option-for-dropbox-filesupload-javascript-api) stackoverflow question

**Comment by paddyroddy** [comment]
Overwriting a file and keep a sharing link is possible with Dropbox. I have a setup in Travis doing this like in this guide https://ljvmiranda921.github.io/notebook/2018/02/04/continuous-integration-for-latex/. I'm trying to convert it to GitHub Actions so this feature is very important to me

**Comment by Remty5** [comment]
Really nice guide you're linking to.
If I'm not mistaken, you're in the process of trying to convert to Github Actions so you're looking at this Action.
But, can't you just use the [shell script](https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh) in your Github Workflow ?
It should work well and looks like a really good replacement.
Thanks for sharing.

**Comment by paddyroddy** [comment]
Yes I think I'll have to in the end. Was hoping there was a pre-built action out there but it doesn't look like it

**Comment by Remty5** [comment]
Well have fun with that, i'll close this issue as it's not looking like this is gonna get addressed any time in the near future.
